### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by test2a** [davidbowland/emails-inbound-service#9]
hi. 

 i have a small usecase for "inbound email processing" and while searching for some tool, i found yours. i have a few questions, if you are kind enough to help me with that.

1. license of the project...
2. my use case is this. i have an email server with multiple email addresses. inbound only. when someone sends a transactional email to it, the server would see a few things including time, reciever and message body.
3. at the same time, a software would send an api call containing a keyword and time to the server.
4. the keyword is the email address which recieved the mail.
5. the server does these things at once. it checks that the api call is recieved. it checks that the email is recieved.
6. the server compares if the keyword in the two match, and the time matches. it parses the email body and sends the "otp" to the api call.
7. i found https://github.com/JayNewstrom/InboundEmail which gives me all inbound emails as a json so i suppose the next step would be to compare the two , maybe your project is better suited as it can do lambda but i am not sure

**Comment by davidbowland** [comment]
You are welcome to use this project as a starter or template for your project. Feel free to fork it!

If you're using SES to process inbound emails, I highly recommend using a lambda for that processing. The serverless nature makes it scalable and cost-effective unless you have massive traffic.

I'm afraid I don't have a lot of time to consult of your project, but I'm confident this project is a good place to start for what you're looking to do. Best of luck to you!
